// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Syncfusion.HelpDesk.Server.HelpDeskRepository
{
    public partial class SyncfusionHelpDeskTickets
    {
        public SyncfusionHelpDeskTickets()
        {
            SyncfusionHelpDeskTicketDetails = new HashSet<SyncfusionHelpDeskTicketDetails>();
        }

        public int Id { get; set; }
        public int ModuleId { get; set; }
        public string TicketStatus { get; set; }
        public DateTime TicketDate { get; set; }
        public string TicketDescription { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }

        public virtual ICollection<SyncfusionHelpDeskTicketDetails> SyncfusionHelpDeskTicketDetails { get; set; }
    }
}